# Generated by Django 4.2.17 on 2024-12-27 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0002_alter_gymclass_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='equipment_needed',
        ),
    ]
