# Generated by Django 4.2.17 on 2024-12-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0003_remove_booking_equipment_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='first_name',
            field=models.CharField(default='FirstName', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='last_name',
            field=models.CharField(default='LastName', max_length=50),
        ),
    ]
