# Generated by Django 4.2.17 on 2024-12-30 16:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Classes', '0004_booking_email_booking_first_name_booking_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymclass',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
